# Generated by Django 3.2.18 on 2023-03-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=35)),
                ('subject', models.TextField(default='')),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=35)),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(default='', max_length=12)),
                ('phone', models.CharField(default='', max_length=30)),
                ('people', models.IntegerField(default='')),
                ('message', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
