# Generated by Django 3.2.18 on 2023-03-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=35)),
                ('message', models.TextField(blank=True, max_length=300, null=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
