# Generated by Django 3.2.18 on 2023-05-22 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cancellation',
        ),
    ]
